# Generated by Django 3.2.7 on 2021-09-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_address1',
            field=models.CharField(max_length=100, verbose_name='Project Address 1'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_address2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Project Address 2'),
        ),
    ]
