# Generated by Django 3.2.7 on 2021-09-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20210910_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_address1',
            field=models.CharField(max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_address2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=' '),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_details',
            field=models.TextField(default=1, verbose_name='Details'),
            preserve_default=False,
        ),
    ]
