# Generated by Django 3.2.7 on 2021-09-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_project_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='clients',
            field=models.ManyToManyField(related_name='project_clients', through='project.ProjectClients', to='project.Client'),
        ),
    ]
