# Generated by Django 3.2.7 on 2021-09-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_project_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='clients',
            field=models.ManyToManyField(related_name='client_projects', through='project.ProjectClients', to='project.Client'),
        ),
    ]
